//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScriptGenerator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScriptGenerator.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- CRZ &lt;CRZ&gt; RzID &lt;RZID&gt;
        ///insert into tb_comercio_Arquivos_Fisco_Resposta([Data],IdReferencia,SituacaoProcessamentoCodigo, SituacaoProcessamentoDescricao, Recibo, Mensagem) 
        ///										 values(&apos;&lt;DATA&gt;&apos;,&apos;&lt;IDREF&gt;&apos;,&apos;&lt;ProcCod&gt;&apos;,&apos;&lt;ProcDesc&gt;&apos;,&apos;&lt;Recibo&gt;&apos;,NULL)
        ///
        ///update tb_comercio_Arquivos_Fisco_ReducaoZ set XmlTransmitido = 1, Protocolo = &apos;&lt;Recibo&gt;&apos; where ReducaoID = &lt;RZID&gt;
        ///update tb_pdv_total_geral set XmlTransmitido = 1 where id = &lt;RZID&gt;.
        /// </summary>
        internal static string InputSQL {
            get {
                return ResourceManager.GetString("InputSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- ACRZ &lt;CRZ&gt; RzID &lt;ID&gt;
        ///update tb_pdv_total_geral set ContadorReducaoZ = &lt;CRZ&gt; where id = &lt;ID&gt;
        ///update tb_comercio_Arquivos_Fisco_ReducaoZ set XmlTransmitido = 0, Protocolo = null where ReducaoID = &lt;ID&gt;.
        /// </summary>
        internal static string ReviewCRZ {
            get {
                return ResourceManager.GetString("ReviewCRZ", resourceCulture);
            }
        }
    }
}
